/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromoPostersRouteImport } from './routes/promo-posters'
import { Route as GifPreviewRouteImport } from './routes/gif-preview'
import { Route as IndexRouteImport } from './routes/index'

const PromoPostersRoute = PromoPostersRouteImport.update({
  id: '/promo-posters',
  path: '/promo-posters',
  getParentRoute: () => rootRouteImport,
} as any)
const GifPreviewRoute = GifPreviewRouteImport.update({
  id: '/gif-preview',
  path: '/gif-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gif-preview': typeof GifPreviewRoute
  '/promo-posters': typeof PromoPostersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gif-preview': typeof GifPreviewRoute
  '/promo-posters': typeof PromoPostersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gif-preview': typeof GifPreviewRoute
  '/promo-posters': typeof PromoPostersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gif-preview' | '/promo-posters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gif-preview' | '/promo-posters'
  id: '__root__' | '/' | '/gif-preview' | '/promo-posters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GifPreviewRoute: typeof GifPreviewRoute
  PromoPostersRoute: typeof PromoPostersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promo-posters': {
      id: '/promo-posters'
      path: '/promo-posters'
      fullPath: '/promo-posters'
      preLoaderRoute: typeof PromoPostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-preview': {
      id: '/gif-preview'
      path: '/gif-preview'
      fullPath: '/gif-preview'
      preLoaderRoute: typeof GifPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GifPreviewRoute: GifPreviewRoute,
  PromoPostersRoute: PromoPostersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
